module.exports = {
  root: true,
  extends: ['@react-native-community', 'prettier'],
  rules: {
    semi: [2, 'always'],
    quotes: [2, 'single', { avoidEscape: true }],
  },
  globals: {
    describe: 'readonly',
    test: 'readonly',
    jest: 'readonly',
    expect: 'readonly',
    fetch: 'readonly',
    navigator: 'readonly',
    waitFor: 'readonly',
    XMLHttpRequest: 'readonly',
    __DEV__: 'readonly',
    FormData: 'readonly',
    React$Element: 'readonly',
    beforeAll: 'readonly',
    beforeEach: 'readonly',
    by: 'readonly',
    element: 'readonly',
    it: 'readonly',
    device: 'readonly',
    afterAll: 'readonly',
    afterEach: 'readonly',
  },
}
