jobs:
- job: Test
  pool:
  # note: both ios and android emulator is only available on mac-os on azure pipelines
    vmImage: 'macOS-10.14'
  variables:
    SCRIPT_DIR: $BUILD_REPOSITORY_LOCALPATH/test/scripts
    JHI_AUTH_TYPE: jwt
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DTO: false
    JHI_WEBSOCKETS: false

  strategy:
    matrix:
      jwt:
        JHI_IGNITE_APP_NAME: JwtApp
        JHI_AUTH_TYPE: jwt
        JHI_DTO: false
      jwt-dto:
        JHI_IGNITE_APP_NAME: JwtDtoApp
        JHI_AUTH_TYPE: jwt
        JHI_DTO: true
      session:
        JHI_IGNITE_APP_NAME: SessionApp
        JHI_AUTH_TYPE: session
        JHI_DTO: false
      session-dto:
        JHI_IGNITE_APP_NAME: SessionDtoApp
        JHI_AUTH_TYPE: session
        JHI_DTO: true
      oauth2:
        JHI_IGNITE_APP_NAME: OauthApp
        JHI_AUTH_TYPE: oauth2
        JHI_DTO: false
      oauth2-dto:
        JHI_IGNITE_APP_NAME: OauthDtoApp
        JHI_AUTH_TYPE: oauth2
        JHI_DTO: true
      jwt-websockets:
        JHI_IGNITE_APP_NAME: JwtWebsocketsApp
        JHI_AUTH_TYPE: jwt
        JHI_DTO: false
        JHI_WEBSOCKETS: true
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'TOOLS: install Node.js'
  - script: npm install -g npm
    displayName: 'TOOLS: update NPM'
  - script: $(SCRIPT_DIR)/install-node-dependencies.sh
    displayName: 'TOOLS: install node dependencies'
  - script: $(SCRIPT_DIR)/install-detox.sh
    displayName: 'TOOLS: installing Detox and its dependencies'
  - script: $(SCRIPT_DIR)/display-tools.sh
    displayName: 'TOOLS: display tools'
  - script: $(SCRIPT_DIR)/copy-jdl-file.sh
    displayName: 'SETUP: copy the JDL file for the backend and app'
  - script: npm ci && npm link
    displayName: 'TOOLS: npm install and link in ignite-jhipster'
  - script: $(SCRIPT_DIR)/generate-jhipster-backend.sh
    displayName: 'PACKAGING: generate jhipster backend'
  - script: $(SCRIPT_DIR)/generate-ignite-jhipster-app.sh
    displayName: 'GENERATING: generate ignite-jhipster app'
  - script: $(SCRIPT_DIR)/package-ignite-jhipster-app.sh
    displayName: 'PACKAGING: package ignite-jhipster app for detox'
#  the generated JHipster backend is packaged after generating the app so changes from ignite-jhipster can be packaged
  - script: $(SCRIPT_DIR)/package-jhipster-backend.sh
    displayName: 'PACKAGING: package jhipster backend'
  - script: $(SCRIPT_DIR)/run-detox-tests.sh
    displayName: 'TESTING: run detox tests'
