name: App Tests
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!dependabot/**'
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  # Group by workflow and ref, limit to 1 for pull requests
  group: ${{ github.workflow }}-${{ github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
  # Cancel intermediate pull request builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  applications:
    name: app-tests-${{ matrix.app_type }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]') && !contains(github.event.ref_type, '[tag]')"
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        node_version: [22]
        app_type:
          - JwtDtoWebsocketsApp
          - OauthFlickrApp
          - OauthHealthPointsApp
        include:
          - app_type: JwtDtoWebsocketsApp
            auth_type: jwt
            dto: true
            websockets: true
            jhipster_version: 8
          - app_type: OauthFlickrApp
            auth_type: oauth2
            dto: false
            entity_jdl: entities-flickr2.jdl
            jhipster_version: 8
          - app_type: OauthHealthPointsApp
            auth_type: oauth2
            dto: false
            entity_jdl: entities-21points.jdl
            jhipster_version: 8
    env:
      JHI_REACT_NATIVE_APP_NAME: ${{ matrix.app_type }}
      JHI_AUTH_TYPE: ${{ matrix.auth_type }}
      JHI_DTO: ${{ matrix.dto }}
      JHI_WEBSOCKETS: ${{ matrix.websockets }}
      JHIPSTER_VERSION: ${{ matrix.jhipster_version }}
      JHI_ENTITY_JDL: ${{ matrix.entity_jdl }}
      SCRIPT_DIR: ./test/scripts
      PLATFORM: ios
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21.x'
      - run: git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node_version }}
      - run: $SCRIPT_DIR/git-config.sh
        name: Config git variables
      - run: npm i && npm link
        name: 'TOOLS: npm install and link in generator-jhipster-react-native'
      - run: $SCRIPT_DIR/copy-jdl-file.sh
        name: 'SETUP: copy the JDL file for the backend and app'
      - run: $SCRIPT_DIR/generate-react-native-app.sh
        name: 'GENERATING: generate react-native app'
      - run: $SCRIPT_DIR/run-react-native-tests.sh
        name: 'TESTING: npm run test'
  applications-result:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [applications]
    if: always()
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          if ([ 'skipped' == '${{ needs.applications.result }}' ] || [ 'success' == '${{ needs.applications.result }}' ]); then
            exit 0
          fi
          if [ 'closed' == '${{ github.event.action }}' ]; then
            exit 0
          fi
          exit 1
